
[package]
name = "LEDboardClient"
version = "0.1.0"
edition = "2021"

[dependencies]
bit = "0.1.1"
embedded-graphics = "0.8.0"
substring = "1.4.5"
tinybmp = "0.5.0"
openweathermap = { path = "../openweathermap" }
chrono = { version = "0.4.23", default-features = false , features = ["iana-time-zone"] }
chrono-tz = "0.8.0"
colored = "2.0.0"
datetime = "0.5.2"
# Necessary for web crawler
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# end of web stuff
